import { ProjectsService } from './projects.service';
export declare class ProjectsController {
    private readonly projectsService;
    constructor(projectsService: ProjectsService);
    findAll(user: {
        userId: string;
    }): Promise<{
        id: any;
        name: any;
        event_type: any;
        event_date: any;
        event_end_date: any;
        guest_count: any;
        status: any;
        total_price: null;
        venue_name: any;
        venue_id: any;
        created_at: any;
        updated_at: any;
    }[]>;
    findOne(id: string, user: {
        userId: string;
    }): Promise<{
        latestActiveContract: {
            id: string;
            title: string | null;
            status: import(".prisma/client").$Enums.contract_status;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            deleted_by: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            project_id: string;
            ai_generated: boolean;
            approved_by_user_id: string | null;
            is_active: boolean;
            version_number: number;
            contract_group_id: string;
            previous_version_id: string | null;
            body: import("@prisma/client/runtime/library").JsonValue;
            pdf_path: string | null;
            total_amount: import("@prisma/client/runtime/library").Decimal | null;
            change_reason: string | null;
            esign_provider: import(".prisma/client").$Enums.esign_provider | null;
            esign_envelope_id: string | null;
            created_by: string;
            seen_by_client_at: Date | null;
            sent_at: Date | null;
            client_signed_at: Date | null;
            expires_at: Date | null;
        } | null;
        id: string;
        owner_user_id: string;
        venue_id: string | null;
        title: string;
        event_date: Date | null;
        event_end_date: Date | null;
        guest_count: number | null;
        status: import(".prisma/client").$Enums.project_status;
        ai_event_summary: string | null;
        created_via_ai_intake: boolean;
        ai_conversation_state_id: string | null;
        signed_contract_id: string | null;
        auto_lock_at: Date | null;
        locked_at: Date | null;
        locked_reason: string | null;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        deleted_by: string | null;
    }>;
    create(user: {
        userId: string;
    }, body: {
        title: string;
        eventDate?: string;
        eventEndDate?: string;
        guestCount?: number;
    }): Promise<{
        id: string;
        owner_user_id: string;
        venue_id: string | null;
        title: string;
        event_date: Date | null;
        event_end_date: Date | null;
        guest_count: number | null;
        status: import(".prisma/client").$Enums.project_status;
        ai_event_summary: string | null;
        created_via_ai_intake: boolean;
        ai_conversation_state_id: string | null;
        signed_contract_id: string | null;
        auto_lock_at: Date | null;
        locked_at: Date | null;
        locked_reason: string | null;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        deleted_by: string | null;
    }>;
    createFromAiIntake(user: {
        userId: string;
    }, body: {
        client_name?: string;
        contact_email?: string;
        contact_phone?: string;
        event_type?: string;
        event_date?: string;
        guest_count?: number;
        service_type?: string;
        menu_items?: string[];
        menu_notes?: string;
        dietary_restrictions?: string[];
        budget_range?: string;
        venue_name?: string;
        venue_address?: string;
        setup_time?: string;
        service_time?: string;
        addons?: string[];
        modifications?: string[];
        thread_id?: string;
        generate_contract?: boolean;
    }): Promise<{
        project: {
            id: string;
            owner_user_id: string;
            venue_id: string | null;
            title: string;
            event_date: Date | null;
            event_end_date: Date | null;
            guest_count: number | null;
            status: import(".prisma/client").$Enums.project_status;
            ai_event_summary: string | null;
            created_via_ai_intake: boolean;
            ai_conversation_state_id: string | null;
            signed_contract_id: string | null;
            auto_lock_at: Date | null;
            locked_at: Date | null;
            locked_reason: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            deleted_by: string | null;
        };
        venue: {
            id: string;
            created_at: Date;
            updated_at: Date;
            name: string;
            address: string | null;
            city: string | null;
            state: string | null;
            country: string;
            contact_name: string | null;
            contact_email: string | null;
            contact_phone: string | null;
            capacity_min: number | null;
            capacity_max: number | null;
            notes: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue;
            active: boolean;
        } | null;
        contract: {
            id: string;
            title: string | null;
            status: import(".prisma/client").$Enums.contract_status;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            deleted_by: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
            project_id: string;
            ai_generated: boolean;
            approved_by_user_id: string | null;
            is_active: boolean;
            version_number: number;
            contract_group_id: string;
            previous_version_id: string | null;
            body: import("@prisma/client/runtime/library").JsonValue;
            pdf_path: string | null;
            total_amount: import("@prisma/client/runtime/library").Decimal | null;
            change_reason: string | null;
            esign_provider: import(".prisma/client").$Enums.esign_provider | null;
            esign_envelope_id: string | null;
            created_by: string;
            seen_by_client_at: Date | null;
            sent_at: Date | null;
            client_signed_at: Date | null;
            expires_at: Date | null;
        } | null;
        contract_data: {
            client_name?: string;
            contact_email?: string;
            contact_phone?: string;
            event_type?: string;
            event_date?: string;
            guest_count?: number;
            service_type?: string;
            menu_items?: string[];
            menu_notes?: string;
            dietary_restrictions?: string[];
            budget_range?: string;
            venue_name?: string;
            venue_address?: string;
            setup_time?: string;
            service_time?: string;
            addons?: string[];
            modifications?: string[];
            thread_id?: string;
            generate_contract?: boolean;
        };
    }>;
}
