-- ========== AI Agent Tables Migration ==========
-- This migration adds minimal tables for the LangGraph AI Agent
-- It integrates with the existing schema without breaking anything
-- 
-- Dependencies:
--   - projects table (already exists)
--   - threads table (already exists)
--   - messages table (already exists)
--   - contracts table (already exists)

-- ========== 1. AI Conversation States ==========
-- Stores slot-filling state for AI-driven lead intake conversations
-- This table tracks structured data extracted from messages for contract generation
CREATE TABLE ai_conversation_states (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id UUID NOT NULL UNIQUE REFERENCES threads(id) ON DELETE CASCADE,
    project_id UUID NULL REFERENCES projects(id) ON DELETE CASCADE,
    
    -- Conversation flow state
    current_node TEXT NOT NULL DEFAULT 'start',  -- collect_name, collect_phone, etc.
    
    -- Slot-filling data (structured information extracted from messages)
    -- This stores the LATEST values for contract generation
    slots JSONB NOT NULL DEFAULT '{
        "name": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "phone": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "event_date": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "service_type": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "event_type": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "venue": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "guest_count": {"value": null, "filled": false, "modified_at": null, "modification_history": []},
        "special_requests": {"value": null, "filled": false, "modified_at": null, "modification_history": []}
    }'::jsonb,
    
    -- Status tracking
    is_completed BOOLEAN NOT NULL DEFAULT false,
    
    -- Next action tracking (for disambiguation flows when user says @AI)
    next_action TEXT NULL,  -- await_clarification, etc.
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for quick lookups
CREATE INDEX ix_ai_conversation_states_thread ON ai_conversation_states (thread_id);
CREATE INDEX ix_ai_conversation_states_project ON ai_conversation_states (project_id);
CREATE INDEX ix_ai_conversation_states_completed ON ai_conversation_states (is_completed, updated_at DESC);

-- GIN index for JSONB slot queries (for fast slot value searches)
CREATE INDEX ix_ai_conversation_states_slots ON ai_conversation_states USING GIN (slots);

COMMENT ON TABLE ai_conversation_states IS 'Tracks slot-filling state for AI lead intake - stores structured data extracted from messages for contract generation';
COMMENT ON COLUMN ai_conversation_states.slots IS 'Structured data extracted from conversation: name, phone, event_date, etc. with modification history for @AI changes';
COMMENT ON COLUMN ai_conversation_states.current_node IS 'Current step in conversation flow (start, collect_name, collect_phone, etc.)';
COMMENT ON COLUMN ai_conversation_states.next_action IS 'Pending action like await_clarification when @AI disambiguation is needed';

-- ========== 2. Integration with existing messages table ==========
-- Add optional column to link messages to AI conversation state
-- This allows tracking which messages belong to AI-driven lead intake
ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS ai_conversation_state_id UUID NULL REFERENCES ai_conversation_states(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_messages_ai_conversation ON messages (ai_conversation_state_id) WHERE ai_conversation_state_id IS NOT NULL;

COMMENT ON COLUMN messages.ai_conversation_state_id IS 'Links message to AI conversation state if part of AI-driven lead intake';

-- ========== 3. Integration with existing projects table ==========
-- Add optional columns to track if project was created via AI intake
-- This is a non-breaking change - adds nullable columns
ALTER TABLE projects 
ADD COLUMN IF NOT EXISTS created_via_ai_intake BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS ai_conversation_state_id UUID NULL REFERENCES ai_conversation_states(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_projects_ai_intake ON projects (created_via_ai_intake) WHERE created_via_ai_intake = true;

COMMENT ON COLUMN projects.created_via_ai_intake IS 'Indicates if project was created through AI-driven lead intake';
COMMENT ON COLUMN projects.ai_conversation_state_id IS 'Links to the AI conversation that created this project';

-- ========== 4. Integration with existing contracts table ==========
-- Add optional column to link contracts to AI conversation
-- This allows tracking which contracts were generated by AI
ALTER TABLE contracts 
ADD COLUMN IF NOT EXISTS ai_conversation_state_id UUID NULL REFERENCES ai_conversation_states(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_contracts_ai_conversation ON contracts (ai_conversation_state_id) WHERE ai_conversation_state_id IS NOT NULL;

COMMENT ON COLUMN contracts.ai_conversation_state_id IS 'Links contract to AI conversation that generated it';

-- ========== 5. Trigger to auto-update conversation_states timestamp ==========
-- Automatically update updated_at on any change
CREATE OR REPLACE FUNCTION update_conversation_state_timestamp()
RETURNS TRIGGER AS $
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_conversation_state_timestamp
BEFORE UPDATE ON ai_conversation_states
FOR EACH ROW
EXECUTE FUNCTION update_conversation_state_timestamp();

COMMENT ON FUNCTION update_conversation_state_timestamp IS 'Auto-updates timestamp on conversation state changes';

-- ========== 6. Helper function to create project from AI conversation ==========
-- Function to convert AI conversation to formal project
CREATE OR REPLACE FUNCTION create_project_from_ai_conversation(
    p_conversation_state_id UUID,
    p_owner_user_id UUID
) RETURNS UUID AS $
DECLARE
    v_project_id UUID;
    v_thread_id UUID;
    v_slots JSONB;
    v_event_date DATE;
    v_guest_count INT;
    v_title TEXT;
BEGIN
    -- Get slots data and thread_id
    SELECT slots, thread_id INTO v_slots, v_thread_id
    FROM ai_conversation_states
    WHERE id = p_conversation_state_id;
    
    -- Extract data from slots
    v_event_date := (v_slots->'event_date'->>'value')::DATE;
    v_guest_count := (v_slots->'guest_count'->>'value')::INT;
    v_title := COALESCE(
        v_slots->'event_type'->>'value' || ' - ' || v_slots->'name'->>'value',
        'New Event'
    );
    
    -- Create project
    INSERT INTO projects (
        owner_user_id,
        title,
        event_date,
        guest_count,
        status,
        created_via_ai_intake,
        ai_conversation_state_id
    ) VALUES (
        p_owner_user_id,
        v_title,
        v_event_date,
        v_guest_count,
        'draft',
        true,
        p_conversation_state_id
    ) RETURNING id INTO v_project_id;
    
    -- Update conversation state with project_id
    UPDATE ai_conversation_states
    SET project_id = v_project_id,
        updated_at = now()
    WHERE id = p_conversation_state_id;
    
    RETURN v_project_id;
END;
$ LANGUAGE plpgsql;

COMMENT ON FUNCTION create_project_from_ai_conversation IS 'Converts completed AI conversation to formal project';

-- ========== End of AI Agent Migration ==========

-- Summary of changes:
-- ✅ Added 1 new table: ai_conversation_states (tracks slot-filling state)
-- ✅ Added 3 nullable columns to existing tables (non-breaking):
--    - messages.ai_conversation_state_id
--    - projects.created_via_ai_intake
--    - projects.ai_conversation_state_id
--    - contracts.ai_conversation_state_id
-- ✅ Added indexes for performance (including GIN index for JSONB queries)
-- ✅ Added trigger for auto-updating conversation state timestamp
-- ✅ Added helper function for project creation from AI conversation
-- ✅ All changes are backward compatible
-- ✅ No existing functionality is broken
-- ✅ AI generates contracts directly to existing contracts table
-- ✅ Messages stored in existing messages table
-- ✅ @AI modifications tracked in slots.modification_history

